name: Bug Report
description: Report a bug or unexpected behavior in the REHAU NEA SMART MQTT Bridge
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have enabled debug logging and reviewed the logs
          required: true
        - label: I have checked the troubleshooting section in the README
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Set temperature to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: How are you running the bridge?
      options:
        - Home Assistant OS Add-on
        - Home Assistant Core (Docker Compose)
        - Home Assistant Core (Docker standalone)
        - Standalone Node.js
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Bridge Version
      description: Version of the REHAU NEA SMART MQTT Bridge
      placeholder: e.g., 2.7.2
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: Version of Home Assistant (if applicable)
      placeholder: e.g., 2024.12.0

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your bridge configuration (redact sensitive information like passwords and email addresses)
      placeholder: |
        ```yaml
        rehau:
          email: your.email@example.com
          password: [REDACTED]
        mqtt:
          host: core-mosquitto
          port: 1883
        log_level: debug
        ```
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please paste relevant log excerpts here. 
        
        **IMPORTANT:** 
        - Enable debug logging (`log_level: debug`) before capturing logs
        - Review logs for personal information (installation names, zone names, etc.) before sharing
        - Only include relevant sections, not entire log files
        - Use code blocks for formatting
      placeholder: |
        ```
        [2024-01-01 12:00:00] INFO: MQTT connected
        [2024-01-01 12:00:01] ERROR: Failed to authenticate with REHAU API
        ...
        ```
      render: text

  - type: textarea
    id: mqtt_topics
    attributes:
      label: MQTT Topics (if applicable)
      description: |
        If the issue is related to MQTT topics or entities, please provide:
        - Affected entity IDs
        - MQTT topic paths
        - Any MQTT messages (redact sensitive data)
      placeholder: |
        Entity ID: climate.rehau_xxx_ground_floor_living_room
        MQTT Topic: homeassistant/climate/rehau_6595d1d5cceecee9ce9772e1/...
      render: text

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - MQTT Broker: Mosquitto / RabbitMQ / Other
        - MQTT Broker Version: (if known)
        - Docker Version: (if using Docker)
        - Node.js Version: (if running standalone)
        - Operating System: (if running standalone)
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might be helpful
      placeholder: Add any other context about the problem here...

