name: Feature Request
description: Suggest a new feature or enhancement for the REHAU NEA SMART MQTT Bridge
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible about what you'd like to see.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have checked the "Future Enhancements" section in the README
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm always frustrated when [...]
        
        Example: I'm always frustrated when I can't control the schedule from Home Assistant, and I have to use the REHAU app instead.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like to see [...]
        
        Example: I would like to see schedule/program support integrated into Home Assistant, so I can set heating schedules directly from the UI.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        Alternative approaches could be [...]
        
        Example: Alternatively, we could expose schedule information as read-only sensors, or provide a REST API endpoint to manage schedules.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my experience
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Climate Control (temperature, mode, preset)
        - Schedule/Program Support
        - Sensors (new sensor types, additional data)
        - MQTT Integration (topic structure, discovery)
        - API/HTTP Endpoints
        - Configuration Options
        - UI/UX Improvements
        - Performance/Optimization
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        Example: When I'm away from home, I want to be able to activate party mode for a specific zone through Home Assistant, so I can prepare the house before arriving.
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details (Optional)
      description: |
        If you have technical knowledge about the REHAU API or protocol, please share relevant details:
        - REHAU API endpoints or commands that might be involved
        - MQTT topic structure suggestions
        - Home Assistant entity types that would be created
        - Any relevant documentation or references
      placeholder: |
        Example:
        - REHAU API endpoint: `/api/v1/zones/{zoneId}/schedule`
        - Would create: `sensor.rehau_xxx_zone_schedule` entities
        - MQTT topic: `homeassistant/sensor/rehau_{zoneId}_schedule/...`
      render: text

  - type: textarea
    id: related_features
    attributes:
      label: Related Features
      description: |
        Does this feature relate to any existing features or planned enhancements?
        - Reference related issues or PRs
        - Mention features from the README's "Future Enhancements" section
      placeholder: |
        Related to:
        - Issue #123
        - "Schedule/Program Support" from Future Enhancements section
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples that might be helpful
      placeholder: Add any other context, screenshots, or examples about the feature request here...

